account/urls.py
from django.urls import path 
from .views import delete_tahseel
from account.api.register import (send_otp_mobile,
                                                 verify_mobile_otp,
                                                 add_profile,
                                                 stateListView,
                                                 districtSerializer,
                                                 tahseelSerializer

                                   
                                   )
from account.api.home.home import home_api
from account.api.search import serach_api 

from account.api.home.requirement import requirement_api , requirement_accepted_api
from account.web.home import (chooselanguage , sendotp, dumydashboard, 
                              verify_otp , 
                                choose_profile , 
                                logout_view ,
                                making_payment,
                                privacypolicy,
                                turmsconditions,
                                cancelandrefund,
                                shippingdelivery,
                                contactus,
                                paymentcondition,
                                home,
                                aboutus,
                                services,
                                contactus,
                                rentaleque,)
from account.web.dashboard import (dashboard ,
                                   vehicels_all_view,
                                   drivers_all_view,
                                   labour_all_view ,
                                   subcontructor_all_view,
                                   categories_view ,
                                   requirement_view ,
                                   requirement_req_view,
                                   requirement_cancle_view)

app_name = 'account'

urlpatterns = [
        ## WEB ############################
        path('delete_tahseel/',delete_tahseel  ),
        path('dumydashboard', dumydashboard, name='dumydashboard'),
        path('dashboard/',dashboard , name="home-dashboard" ),
        path('chooselanguage/' , chooselanguage, name="chooselanguage") ,
        path('web-send-otp/' , sendotp , name="send-otp") ,
        path('verify-otp/' , verify_otp , name="verify-otp") ,
        path('choose-profile/' , choose_profile , name="choose-profile") ,
        path('logout-view/' , logout_view , name="logout_view") ,
        path('making_payment/',making_payment, name="making_payment"),
        #View All
        path('vehicels-all-view/',vehicels_all_view, name="vehicels_all_view"),
        path('drivers-all-view/',drivers_all_view, name="drivers_all_view"),
        path('labours-all-view/',labour_all_view, name="labour_all_view"),
        path('subcontructors-all-view/',subcontructor_all_view, name="subcontructor_all_view"),

        #categories
        path('categories/',categories_view, name="categories_view"),
        # Requiremnt
        path('requirement/',requirement_view, name="requirement_view"),
        path('requirement-request/<int:pk>/',requirement_req_view, name="requirement_req_view"),
        path('requirement-cancel/<int:pk>/',requirement_cancle_view, name="requirement_cancle_view"),
        
        ## END WEB 


        ### API   
        path('send-otp/' , send_otp_mobile ) ,
        path('verify-mobile-otp/' , verify_mobile_otp ) ,
        path('add-profile/', add_profile), 
        path('states/', stateListView.as_view()),
        # path('districts/', districtSerializer.as_view()),
        path('states/<int:id>/districts/', districtSerializer.as_view()),
        path('districts/<int:id>/tahseel/', tahseelSerializer.as_view()),
        path('serach_api/', serach_api),
        
        ## Home 
        path('home-api/' , home_api) ,


        ## requirement

        path('requirement-api/' , requirement_api),
        path('requirement-accepted-api/' , requirement_accepted_api),
        
        # Add all privacy policy
        
        path('', home,),

        
        path('privacypolicy/', privacypolicy, name="privacypolicy"),
        path('turmscondition/', turmsconditions, name="turmscondition"),
        path('cancelrefund/', cancelandrefund, name="cancelrefund"),
        path('shippingdelivery/', shippingdelivery, name="shippingdelivery"),
        path('contactus/', contactus, name="contactus"),
        path('payment/', paymentcondition, name="payment"),
        path('aboutus/', aboutus, name="aboutus"),
        path('services/', services, name="services"),
        path('contactus/', contactus, name="contactus"),
        path('rentaleque/', rentaleque, name="rentaleque"),
        

        

        

    
]

driver/urls.py
from django.urls import path 
from driver.api.register.register import driver_registration, driveraddress , driverdashboard
from driver.api.payment.payment import driver_payment_api , driver_phonepe_handller
from driver.api.register.update_driver import driver_update_api

from driver.api.requested_driver.req_driver import request_driver_api
from driver.web.driver import (
    add_driver_view ,
    add_driver_address ,
    update_driver_profile
)
from driver.web.driver_payment import driver_making_payment , driver_payhandler
from driver.web.dashboard import driver_dashboard , driver_view
from driver.web.driver_request import driver_request_view
app_name = 'driver'

urlpatterns = [
        ### WEb 
        path('add-driver/', add_driver_view , name="add_driver_view"),
        path('add-driver-address/', add_driver_address , name="add_driver_address"),
        path('update-driver-profile/<int:pk>/', update_driver_profile , name="update_driver_profile"),
        path('driver-payment/' , driver_making_payment , name="driver_making_payment") ,
        path('driver-payhandler/', driver_payhandler , name="driver_payhandler"),
        path('driver-web-dashboard/' , driver_dashboard , name="driver_dashboard"),
        path('driver-view/<int:pk>/' , driver_view , name="driver_view"),
        path('driver_request_view/<int:pk>/' , driver_request_view , name="driver_request_view"),
        ### APIS 
        path('driver-registration/' , driver_registration) ,
        path('driver_add_address/', driveraddress),
        path('driver-payment-api/' ,driver_payment_api) ,
        path('driver-phonepe-handller/' ,driver_phonepe_handller) ,
        # path('driver-paymenthandller/' ,driver_paymenthandller) ,
        path('driver-dashboard/' ,driverdashboard ) ,
        path('request-driver/' , request_driver_api),
        path('driver-update-api/' , driver_update_api),
]

forms/account/urls.py
from django.urls import path 
from .views import delete_tahseel
from account.api.register import (send_otp_mobile,
                                                 verify_mobile_otp,
                                                 add_profile,
                                                 stateListView,
                                                 districtSerializer,
                                                 tahseelSerializer

                                   
                                   )
from account.api.home.home import home_api
from account.api.search import serach_api 

from account.api.home.requirement import requirement_api , requirement_accepted_api
from account.web.home import (chooselanguage , sendotp, dumydashboard, 
                              verify_otp , 
                                choose_profile , 
                                logout_view ,
                                making_payment,
                                privacypolicy,
                                turmsconditions,
                                cancelandrefund,
                                shippingdelivery,
                                contactus,
                                paymentcondition,)
from account.web.dashboard import (dashboard ,
                                   vehicels_all_view,
                                   drivers_all_view,
                                   labour_all_view ,
                                   subcontructor_all_view,
                                   categories_view ,
                                   requirement_view ,
                                   requirement_req_view,
                                   requirement_cancle_view)

app_name = 'account'

urlpatterns = [
        ## WEB ############################
        path('delete_tahseel/',delete_tahseel  ),
        path('', dumydashboard),
        path('dashboard/',dashboard , name="home-dashboard" ),
        path('chooselanguage/' , chooselanguage, name="chooselanguage") ,
        path('web-send-otp/' , sendotp , name="send-otp") ,
        path('verify-otp/' , verify_otp , name="verify-otp") ,
        path('choose-profile/' , choose_profile , name="choose-profile") ,
        path('logout-view/' , logout_view , name="logout_view") ,
        path('making_payment/',making_payment, name="making_payment"),
        #View All
        path('vehicels-all-view/',vehicels_all_view, name="vehicels_all_view"),
        path('drivers-all-view/',drivers_all_view, name="drivers_all_view"),
        path('labours-all-view/',labour_all_view, name="labour_all_view"),
        path('subcontructors-all-view/',subcontructor_all_view, name="subcontructor_all_view"),

        #categories
        path('categories/',categories_view, name="categories_view"),
        # Requiremnt
        path('requirement/',requirement_view, name="requirement_view"),
        path('requirement-request/<int:pk>/',requirement_req_view, name="requirement_req_view"),
        path('requirement-cancel/<int:pk>/',requirement_cancle_view, name="requirement_cancle_view"),
        
        ## END WEB 


        ### API   
        path('send-otp/' , send_otp_mobile ) ,
        path('verify-mobile-otp/' , verify_mobile_otp ) ,
        path('add-profile/', add_profile), 
        path('states/', stateListView.as_view()),
        # path('districts/', districtSerializer.as_view()),
        path('states/<int:id>/districts/', districtSerializer.as_view()),
        path('districts/<int:id>/tahseel/', tahseelSerializer.as_view()),
        path('serach_api/', serach_api),
        
        ## Home 
        path('home-api/' , home_api) ,


        ## requirement

        path('requirement-api/' , requirement_api),
        path('requirement-accepted-api/' , requirement_accepted_api),
        
        # Add all privacy policy
        
        path('privacypolicy/', privacypolicy, name="privacypolicy"),
        path('turmscondition/', turmsconditions, name="turmscondition"),
        path('cancelrefund/', cancelandrefund, name="cancelrefund"),
        path('shippingdelivery/', shippingdelivery, name="shippingdelivery"),
        path('contactus/', contactus, name="contactus"),
        path('payment/', paymentcondition, name="payment"),

        

        

    
]

penal/urls.py
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path(_('admin/'), admin.site.urls),
    
]
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('' , include('account.urls' , namespace="account")) ,
    path('' , include('df_user.urls' , namespace="df_user")) ,
    path('' , include('driver.urls' , namespace="driver")) ,
    path('' , include('labour_contructor.urls' , namespace="labour_contructor")) ,
    path('' , include('sub_contructor.urls' , namespace="sub_contructor")) ,
    path('' , include('vehicle_owner.urls' , namespace="vehicle_owner")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sub_contructor/urls.py
from django.urls import path 


from sub_contructor.api.register.register import subcontructor_registration ,subcontructor_Address , subcontructordashboard
from sub_contructor.api.payment.payment import subcontructor_payment_api , subcontructor_paymenthandller
from sub_contructor.api.requested_subcon.req_subcon import request_subcontructor_api
from sub_contructor.api.register.update_subcontructor import subcontructor_update_api


## WEB URLS IMORT

from sub_contructor.web.sub import add_subcontructor_view , add_subcontructor_address, update_subcotructor_profile
from sub_contructor.web.sub_payment import subcontructor_making_payment,subcontrctor_payhandler
from sub_contructor.web.subconturctor_request import request_subcontructor_view
from sub_contructor.web.dashboard import subcontructor_dashboard , subcontructor_view



# from driver.api.payment.payment import driver_paymenthandller , driver_payment_api
app_name = 'sub_contructor'

urlpatterns = [
        
        ## Web 

        path('add-subcontructor/' , add_subcontructor_view , name="add_subcontructor_view"),
        path('add-subcontructor-address/' , add_subcontructor_address , name="add_subcontructor_address"),
        path('update-subcontructor-profile/<int:pk>/' , update_subcotructor_profile , name="update_subcotructor_profile"),

        path('subcontructor-view/<int:pk>/' , subcontructor_view , name="subcontructor_view"),
        path('subcontructor_request_view/<int:pk>/' , request_subcontructor_view , name="subcontructor_request_view"),

        path('subcontructor-web-dashboard/' , subcontructor_dashboard , name="subcontructor_dashboard"),

        path('subcontructor-payment/' , subcontructor_making_payment , name="subcontructor_making_payment"),
        path('subcontructor-payhandler/', subcontrctor_payhandler , name="subcontrctor_payhandler"),

        

        ## APIS

        path('subcontructor-registration/' , subcontructor_registration) ,
        path('subcontructor_Address/', subcontructor_Address),
        path('subcontructor-payment-api/' ,subcontructor_payment_api) ,
        path('subcontructor-paymenthandller/' ,subcontructor_paymenthandller) ,
        path('request-subcontructor/' , request_subcontructor_api) ,
        path('subcontructor-dashboard/' ,subcontructordashboard ) ,
        path('subcontructor_update_api/' , subcontructor_update_api),


]

vehicle_owner/urls.py
from django.urls import path 
from vehicle_owner.api.register.register import (hvregistration , 
                                                 hvaddress ,
                                                 vehicle_user_data,
                                                 letest_vehicle_data
                                                 )
from vehicle_owner.api.payment.payment import makepaymentapi , paymenthandller
from vehicle_owner.api.requested_vehicle.rv import request_vehicle_api

from vehicle_owner.web.vehicle import (add_vehicle_view,
                                       add_heavy_address,
                                       get_districts ,
                                       get_tehsils ,
                                       update_vehicle,
                                       )
from vehicle_owner.api.register.update_vehicle import update_vehicle_api

from vehicle_owner.web.vehicle_payment import vehicle_making_payment , vehicle_payhandler, godashboard
from vehicle_owner.web.dashboard import vehicle_dashboard,vehicle_view
from vehicle_owner.web.vehicle_request import vehicle_request_view
app_name = 'vehicle_owner'
urlpatterns = [

    ##############    WEB  #########################################
    
    # dashboard 
    path('vehicle-dashboard/' , vehicle_dashboard , name="vehicle_dashboard"),
    path('vehicle-view/<int:pk>/' , vehicle_view , name="vehicle_view"),
    # path('vehicle-profile/' , vehicle_profile , name="vehicle_profile"),
    
    ## request vehicle
    path('vehicle_request_view/<int:pk>/' , vehicle_request_view , name="vehicle_request_view"),
    
    ## vehicle
    path('add-heavy-vehicle/' , add_vehicle_view , name="add_vehicle_view"),
    path('add-heavy-address/<int:pk>/' , add_heavy_address , name="add_heavy_address"),
    path('update-vehicle/<int:pk>/' , update_vehicle , name="update_vehicle"),
    
    path('get_districts/' , get_districts , name="get_districts") ,
    path('get_tehsils/',get_tehsils,name="get_tehsils"),
    
    path('vehicle-payment/<int:pk>/',vehicle_making_payment,name="vehicle_making_payment"),
    path('vehicle-payhandler/',vehicle_payhandler,name="vehicle_payhandler"),
    path('godashboard/', godashboard, name="godashboard"),


    ### APIs
    path('add-vehicle/', hvregistration), 
    path('add-address/', hvaddress), 
    path('vehicle-user-data/', vehicle_user_data),     
    path('letest-vehicle-data/' , letest_vehicle_data),
    path('makepayment-api/' , makepaymentapi),
    path('paymenthandller' , paymenthandller),
    path('request-vehicle/',request_vehicle_api),
    # update vehicle 
    path('update-vehicle-api/' , update_vehicle_api ) ,
    



]

account/views.py
from all_import.all_import import *

# Create your views here.
def delete_tahseel(request):
    tahseel.objects.all().delete()
    return redirect('account:dashboard')

forms/account/views.py
from all_import.all_import import *

# Create your views here.
def delete_tahseel(request):
    tahseel.objects.all().delete()
    return redirect('account:dashboard')

account/templates/olddashboard.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

 
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="owl-carousel">
                    <div class="image-aspect">
                        <img src="/static/images/bulldozer-410118_1280.png" alt="">
                    </div>
                    <div class="image-aspect">
                        <img src="/static/images/bulldozer-410118_1280.png" alt="">
                    </div>
                    <div class="image-aspect">
                        <img src="/static/images/asiyai/static/images/bulldozer-410118_1280.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>

        <!-- Heavy Vehicles -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-dark card-outline">
              <div class="card-header font-weight-bold d-flex">
                Heavy Vehicles
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  View All
</button>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for i in MasterContents %}
                   <h1>{{i.key}}</h1>
                  {% endfor  %}
                  {% for i in vehicles %}
                  
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="card">
                          <div class="image-aspect">
                            {% if i.vehicle_image %}
                            <img src="{{i.vehicle_image.url}}" class="card-img-top" alt="...">
                            {% else %}
                            
                            <img src="{{image}}" class="card-img-top" alt="...">

                            {% endif %}
                          </div>
                          <div class="card-body">
                            <h5 class="card-title font-weight-bold">Vehicle Name : 
                              {{i.vehical_name}}</h5>
                            <p class="card-text mb-0">Model Name : {{i.vehiclemodelnumber}}</p>

                            <p class="card-text mb-0">Manufectoring Year : {{i.manufacture_date}}</p>
                            {% for address in i.vehicleaddress.all %}
                            <p class="card-text mb-0">Location:{{address.state_id}}-{{address.district_id}}</p>
                            {% endfor %}

              
                            <!-- <p class="card-text font-weight-bold">Aadhar Number : {{i.Aadhar_number}}</p> -->
                            <a href="{% url 'vehicle_owner:vehicle_view' i.id %}" class="btn btn-sm btn-success elevation-2">View More</a>
                          </div>
                        </div>
                    </div>
                    {% empty %}
                      <div>No Data</div>
                    {% endfor %}

                  </div>
                </div>
              </div>
            
            </div><!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          
        </div>
        <!-- /.row -->

        <!-- Driver/Operator -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-dark card-outline">
              <div class="card-header font-weight-bold d-flex">
                Driver/Operator
                <a class="btn btn-sm btn-dark bg-yellow ml-auto" href="{% url 'account:drivers_all_view'%}">View All</a>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for i in MasterContents %}
                  <h1>{{i.key}}</h1>
                  {% endfor  %}
                  {% for i in drivers %}
                      <div class="col-lg-3 col-md-3 col-sm-12">
                          <div class="card">
                            <div class="image-aspect">
                              {% if i.driver_image %}
                                <img src="{{i.driver_image.url}}" class="card-img-top" alt="...">
                              {%else%}:
                                <img src="" class="card-img-top" alt="...">
                              {% endif %}
                            </div>
                            <div class="card-body">
                              <h5 class="card-title font-weight-bold">Driver/Operator Name : {{i.driveroperatorname}}</h5>
                              <p class="card-text mb-0">Vehicle Name : {{i.vehicalname}}</p>
                              <p class="card-text mb-0">Experience In Years : {{i.expriencesinyear}}</p>
                              <p class="card-text mb-0">Heavy_License : {{i.heavy_license}}</p>
                              {% for ad in i.driverAddress.all %}
                              <p class="card-text mb-0">Location : {{ad.state_id}} {{ad.district_id}}</p>
                              {% endfor %}
                              {% comment %} <p class="card-text mb-0">Approved : {{i.approved}}</p> {% endcomment %}

                              <a href="{% url 'driver:driver_view' i.id %}" class="btn btn-sm btn-success elevation-2">View More</a>
                            </div>
                          </div>
                      </div>
                      {% empty %}
                      <div>No Data</div>
                  {% endfor %}
                </div>
                
               
              </div>
            </div><!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          
        </div>
        <!-- /.row -->

        <!-- Sub Contractor -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-dark card-outline">
              <div class="card-header font-weight-bold d-flex">
                Sub Contractor
                <a class="btn btn-sm btn-dark bg-yellow ml-auto" href="{% url 'account:subcontructor_all_view'%}">View All</a>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for i in MasterContents %}
                    <h1>{{i.key}}</h1>
                  {% endfor  %}
                  {% for i in sub_set %}
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="card">
                          <div class="image-aspect">
                            {% if i.subcontractor_image %}
                              <img src="{{i.subcontractor_image.url}}" class="card-img-top" alt="...">
                            {% else %}
                              <img src="" class="card-img-top" alt="...">
                            {%endif%}
                          </div>
                          <div class="card-body">
                            <h5 class="card-title font-weight-bold">SubContructor Name : {{i.contractorname}}</h5>
                            <p class="card-text mb-0">Firm Name : {{i.firmname}}</p>
                            <p class="card-text mb-0">Type Of Work : {{i.typeofwork}}</p>
                            <p class="card-text mb-0">Experience In Years : {{i.expriencesinyear}}</p>
                            {% for ad in i.SubcotructorAddress.all %}
                            <p class="card-text mb-0">Location : {{ad.state_id}} {{ad.district_id}}</p>
                            {% endfor %}                            
                            <a href="{% url 'sub_contructor:subcontructor_view' i.id %}" class="btn btn-sm btn-success elevation-2">View More</a>
                          </div>
                        </div>
                    </div>
                     {% empty %}
                      <div>No Data</div>
                    {% endfor %}
                  </div>
                  
                </div>
              </div>
            </div><!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          
        </div>
        <!-- /.row -->

        <!-- Labour Contractor -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-dark card-outline">
              <div class="card-header font-weight-bold d-flex">
                Labour Contractor
                <a class="btn btn-sm btn-dark bg-yellow ml-auto elevation-2" href="{% url 'account:labour_all_view' %}">View All</a>
              </div>
              <div class="card-body">
                <div class="row">
                  {% for i in MasterContents %}
                  <h1>{{i.key}}</h1>
                  {% endfor  %}
                  {% for i in labours %}
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="card">
                          
                          <div class="image-aspect">
                            {% if i.labour_image %}
                              <img src="{{i.labour_image.url}}" class="card-img-top" alt="...">
                            {% else %}
                              <img src="" class="card-img-top" alt="...">

                            </div>
                            {% endif %}
                          </div>
                          <div class="card-body">
                            <h5 class="card-title font-weight-bold">Contructor Name : {{i.labourcontractorname}}</h5>
                            <p class="card-text mb-0">Type Of Work : {{i.labourwork}}</p>
                            <p class="card-text mb-0">Labour(InNumber) : {{i.lobourinnumber}}</p>

                            {% for ad in i.labourAddress.all %}
                              <p class="card-text mb-0">Location : {{ad.state_id}} {{ad.district_id}}</p>
                            {% endfor %}
                            <a href="{% url 'labour_contructor:labour_view' i.id %}" class="btn btn-sm btn-success elevation-2">View More</a>
                          </div>
                        </div>
                    </div>
                    {% empty %}
                      <div>No Data</div>
                    {% endfor %}
                </div>
              </div>
            </div><!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="js/adminlte.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

<script>
    var $owl = $('.owl-carousel');

    $owl.children().each( function( index ) {
        $(this).attr( 'data-position', index ); // NB: .attr() instead of .data()
    });

    $owl.owlCarousel({
        center: true,
        loop: true,
        dots: true,
        slideTransition: 'linear',
        autoplay:true,
        autoplayTimeout:3000,
        autoplaySpeed: 500,
        items: 3,
        responsive: {
        0: {
          items: 1,
          nav: false,
          loop: true,
        },
        600: {
          items: 2,
          nav: false,
          loop: true,
        },
        1000: {
          items: 2,
          nav: false,
          loop: true,
        },
      },
    });

    $(document).on('click', '.owl-item>div', function() {
        var $speed = 500;  //in ms
        $owl.trigger('to.owl.carousel', [$(this).data( 'position' ), $speed] );
    });
</script>

{% endblock %}