driver/urls.py
from django.urls import path 
from driver.api.register.register import driver_registration, driveraddress , driverdashboard
from driver.api.payment.payment import driver_payment_api , driver_phonepe_handller
from driver.api.register.update_driver import driver_update_api

from driver.api.requested_driver.req_driver import request_driver_api
from driver.web.driver import (
    add_driver_view ,
    add_driver_address ,
    update_driver_profile
)
from driver.web.driver_payment import driver_making_payment , driver_payhandler
from driver.web.dashboard import driver_dashboard , driver_view
from driver.web.driver_request import driver_request_view
app_name = 'driver'

urlpatterns = [
        ### WEb 
        path('add-driver/', add_driver_view , name="add_driver_view"),
        path('add-driver-address/', add_driver_address , name="add_driver_address"),
        path('update-driver-profile/<int:pk>/', update_driver_profile , name="update_driver_profile"),
        path('driver-payment/' , driver_making_payment , name="driver_making_payment") ,
        path('driver-payhandler/', driver_payhandler , name="driver_payhandler"),
        path('driver-web-dashboard/' , driver_dashboard , name="driver_dashboard"),
        path('driver-view/<int:pk>/' , driver_view , name="driver_view"),
        path('driver_request_view/<int:pk>/' , driver_request_view , name="driver_request_view"),
        ### APIS 
        path('driver-registration/' , driver_registration) ,
        path('driver_add_address/', driveraddress),
        path('driver-payment-api/' ,driver_payment_api) ,
        path('driver-phonepe-handller/' ,driver_phonepe_handller) ,
        # path('driver-paymenthandller/' ,driver_paymenthandller) ,
        path('driver-dashboard/' ,driverdashboard ) ,
        path('request-driver/' , request_driver_api),
        path('driver-update-api/' , driver_update_api),
]

penal/urls.py
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path(_('admin/'), admin.site.urls),
    
]
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('' , include('account.urls' , namespace="account")) ,
    path('' , include('df_user.urls' , namespace="df_user")) ,
    path('' , include('driver.urls' , namespace="driver")) ,
    path('' , include('labour_contructor.urls' , namespace="labour_contructor")) ,
    path('' , include('sub_contructor.urls' , namespace="sub_contructor")) ,
    path('' , include('vehicle_owner.urls' , namespace="vehicle_owner")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

driver/models.py
from django.db import models
from account.models import *


#############driver operator registrations class #####################
class driver_profile(models.Model):
    user                    = models.ForeignKey(User , on_delete=models.CASCADE)
    vehicalname             = models.CharField(max_length=200)
    expriencesinyear        = models.IntegerField(blank=False, null=False)
    driveroperatorname      = models.CharField(max_length=200)
    Aadharnumberfrontimage  = models.ImageField(upload_to="static/Uploaded/UserProfiles/")
    Aadharnumberbackimage   = models.ImageField(upload_to="static/Uploaded/UserProfiles/")
    alternet_mobilenumber   = models.CharField(max_length=12 ,  null=True , blank=True)
    heavy_license           = models.CharField(max_length=50)
    emailId                 = models.EmailField(max_length=100 , null=True , blank=True)
    mobilenumber            = models.CharField(max_length=20)
    license_image           = models. ImageField(upload_to="static/Uploaded/UserProfiles/")
    driver_image            = models.ImageField(upload_to="static/Uploaded/UserProfiles/")
    is_active               = models.BooleanField(default=True)
    driver_paid             = models.BooleanField(default=False)   
    expired_at              = models.DateField(null=True , blank=True)
    class Meta:
        verbose_name_plural = 'Driver Profile'
        db_table = "driveroperatorregistration"
    def __str__(self):
        return self.driveroperatorname +' > '+ self.mobilenumber


############ driver addresss ##############
class driver_Address(models.Model):
    user = models.ForeignKey(driver_profile , on_delete=models.CASCADE, related_name="driverAddress")
    state_id = models.ForeignKey(state , on_delete=models.CASCADE)
    district_id = models.ForeignKey(district , on_delete=models.CASCADE)
    tahseel_id = models.ForeignKey(tahseel , on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    
    
    class Meta:
        verbose_name_plural = 'Driver Address'
        db_table = 'driveraddress'


class driver_payment_amount(models.Model):
    value = models.IntegerField()
    
    
    class Meta:
        verbose_name_plural =  "Add  Payment For Driver"
        db_table = 'driver_payment_amount'



class driver_payment(models.Model):
    user = models.ForeignKey(driver_profile ,
                              on_delete=models.CASCADE , 
                              related_name="driver_payment") 
    razorpay_order_id =  models.CharField(max_length=100)

    payment_id = models.CharField(max_length=100 , null=True , blank=True)
    
    amount =  models.IntegerField()
    discount = models.IntegerField(default=0)

    status = models.BooleanField(default=False)

    recycle = models.IntegerField(default=1)

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural =  "Driver Payment"
        db_table = 'driver_payment'


class request_driver(models.Model):
    user =  models.ForeignKey(profileofall ,  
                              on_delete=models.CASCADE ,
                              )
    driver_profile = models.ForeignKey(driver_profile ,  
                                                on_delete=models.CASCADE ,
                                                related_name= "requested_driver"
                                                 
                                                 )
    reserved = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural =  "Requested Driver"
        db_table = 'request_driver'

    def __str__(self):
        return self.user.user.first_name +" >>"+ self.driver_profile.driveroperatorname

driver/forms.py
from .models import *
from django import forms



class AddDriverForm(forms.ModelForm):
    class Meta:
        model = driver_profile
        exclude = ('user', 'expired_at','driver_paid' ,'is_active')

        widgets = {
            'vehicalname':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'expriencesinyear':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'driveroperatorname':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'Aadharnumberfrontimage':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'Aadharnumberbackimage':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'alternet_mobilenumber':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'heavy_license':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'emailId':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'mobilenumber':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'license_image':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'driver_image':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),         
        }

        

driver/views.py
from django.shortcuts import render

# Create your views here.

driver/templates/driver-profile.html
{% extends "base.html" %}
{% load static %} 
{% block content %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{request.user.first_name}} Profile</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Driver Profile</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">
                <!-- Profile Image -->
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light d-flex">
                        <!-- <div class="card-title">
                            <i class="fas fa-newspaper" style="margin-right: 5px;"></i>
                            Edit News
                        </div> -->

                        <div class="mr-auto">
                          <span class="font-weight-bold">Current Status : </span> 
                          <span class="badge rounded-pill pt-1 pb-1 pl-3 pr-3 badge-info elevation-1">Active</span>
                        </div>

                        <div class="ml-auto">
                          <a class="btn btn-sm btn-primary" href="{% url 'driver:update_driver_profile' driver.id %}"><i class="nav-icon fas fa-edit" style="margin-right: 5px;"></i>Edit Profile</a>
                        </div>
                    </div>

                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="{{driver.driver_image.url}}" alt="User-Profile-Picture">
                        </div>

                        <h3 class="profile-username text-center">{{driver.driveroperatorname}}</h3>
                        <hr>

                        <div class="row">
                          <div class="col-lg-6 col-md-6">
                           
                            <div class="form-group">
                              <label class="font-weight-bold">Mobile Number : </label>
                              <label>{{request.user.mobile_number}}</label>
                            </div>
                            <div class="form-group">
                              <label class="font-weight-bold">Alternet Number : </label>
                              <label>{{driver.alternet_mobilenumber}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Email Address : </label>
                                <label>{{driver.emailId}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Heavy License : </label>
                                <label>{{driver.heavy_license}}</label>
                            </div>
                            <div class="form-group">
                              <label class="font-weight-bold">Payment Status : </label>
                              <span class="badge rounded-pill pt-1 pb-1 pl-3 pr-3 badge-success elevation-1">Paid</span>
                            </div>
                          </div>

                          <div class="col-lg-6 col-md-6">
                            
                            <div class="form-group">
                              <label class="font-weight-bold">Vehicle Name : </label>
                              <label>{{driver.vehicalname}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Expriences in Year : </label>
                                <label>{{driver.expriencesinyear}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Expired  Date : </label>
                                <label>{{driver.expired_at}}</label>
                            </div>
                           
                          
                          </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Aadhar Card Front Side
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{driver.Aadharnumberfrontimage.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Aadhar Card Back Side
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{driver.Aadharnumberbackimage.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Vehicle Front Side Photo
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{driver.license_image.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
            </div>

           
        </div>
        <!-- /.row -->

      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock %}

driver/templates/driver-view.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Driver/Operator Details</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Driver/Operator Details</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>{{message}}</h2>
      <div class="container-fluid">

        <!-- Heavy Vehicles -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Heavy Vehicles -->
                <div class="card card-dark card-outline">
                    <div class="card-body">
                      {% comment %} {% for i in dr %} {% endcomment %}
                        <div class="row">
                          <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="outer">
                              <div id="big" class="owl-carousel owl-theme">
                              {% if dr.driver_image %}
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                              {% comment %} {%else%} {% endcomment %}
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                              {% comment %} {% endif %} {% endcomment %}
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                              </div>

                              <div id="thumbs" class="owl-carousel owl-theme">
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                                <div class="item image-aspect">
                                  <img src="{{dr.driver_image.url}}" class="rounded rounded-5">
                                </div>
                                {% else %}
                                  <img src="" class="rounded rounded-5">
                                {% endif %}
                              </div>
                            </div>
                          </div>

                          <div class="col-lg-6 col-md-6 col-sm-12">
                            
                              <p class="card-text mb-0"></p>
                              
                              <div class="card card-dark shadow">
                                  <div class="card-header">
                                      <h6 class="card-title"><i class="fas fa-user-circle mr-2"></i>Owner and Vehicle Details</h6>
          
                                      <div class="card-tools">
                                          <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                          <i class="fas fa-minus"></i>
                                          </button>
                                      </div>
                                      <!-- /.card-tools -->
                                  </div>
                                  <!-- /.card-header -->

                                  <div class="card-body">
                                        <p class="card-text font-weight-bold">Driver/Operator Name &nbsp;:&nbsp; {{dr.driveroperatorname}}</h5>

                                        <p class="card-text mb-0">Vehicle Name &nbsp; : &nbsp; {{dr.vehicalname}}</p>
                                        <p class="card-text mb-0">Your Experiences &nbsp;:&nbsp; {{dr.expriencesinyear}}</p>
                                        <p class="card-text mb-0">Heavy_License &nbsp;:&nbsp; {{dr.heavy_license}}</p>
                                        {% for ad in dr.driverAddress.all %}
                                        <p class="card-text">Location &nbsp; : &nbsp; {{ad.state_id}} {{ad.district_id}}</p>
                                         {% endfor %}
                                        {% if reh.reserved %}
                                        <p class="card-text font-weight-bold">Status &nbsp;:&nbsp; Reserved</p>
                                        <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Reserved</a></button>
                                    {% else %}
                                    
                                      {% if request.user == dr.user %}
                                      <p class="card-text font-weight-bold">Status &nbsp;: &nbsp; Not Reserved</p>
                                      <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Request</a></button>

                                      {% else %}

                                        {% if request.user == reh.user.user %}
                                        <p class="card-text font-weight-bold">Status: Not Reserved</p>
                                        <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Pending</a></button>

                                        {% else %}

                                        <p class="card-text font-weight-bold">Status: Not Reserved</p>
                                        <a class="btn bg-yellow elevation-2" href="{% url 'driver:driver_request_view' dr.id %}">
                                          Request
                                        </a>
                                       
                                        
                                        {% endif %}

                                        

                                      {% endif %}



                                    {% endif %}
                                        
                                      <a href="{% url 'driver:driver_dashboard' %}" class="btn btn-danger elevation-2 ml-2">Go Back</a>
                                  </div>
                                  
                                  <!-- /.card-body -->
                              </div>
                            </div>
                              <!-- /.card -->
                              {% comment %} {% endfor %} {% endcomment %}
                           
                          </div>
                    </div>
                </div><!-- /.card -->
            </div>
            </div>
            <!-- /.col-md-12 -->
        </div>
        <!-- /.row -->
      </form>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/js/adminlte.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.3/owl.carousel.min.js"></script>

<script>
    $(document).ready(function() {
        var bigimage = $("#big");
        var thumbs = $("#thumbs");
        var syncedSecondary = true;

        bigimage
          .owlCarousel({
          items: 1,
          slideSpeed: 2000,
          nav: true,
          autoplay: true,
          dots: false,
          loop: true,
          responsiveRefreshRate: 200,
          navText: [
            '<i class="fa fa-arrow-left" aria-hidden="true"></i>',
            '<i class="fa fa-arrow-right" aria-hidden="true"></i>'
          ]
        })
          .on("changed.owl.carousel", syncPosition);

        thumbs
          .on("initialized.owl.carousel", function() {
          thumbs
            .find(".owl-item")
            .eq(0)
            .addClass("current");
        })
          .owlCarousel({
          items: 3,
          dots: true,
          nav: true,
          navText: [
            '<i class="fa fa-arrow-left" aria-hidden="true"></i>',
            '<i class="fa fa-arrow-right" aria-hidden="true"></i>'
          ],
          smartSpeed: 200,
          slideSpeed: 500,
          slideBy: 4,
          responsiveRefreshRate: 100
        })
          .on("changed.owl.carousel", syncPosition2);

        function syncPosition(el) {
          //if loop is set to false, then you have to uncomment the next line
          //var current = el.item.index;

          //to disable loop, comment this block
          var count = el.item.count - 1;
          var current = Math.round(el.item.index - el.item.count / 2 - 0.5);

          if (current < 0) {
            current = count;
          }
          if (current > count) {
            current = 0;
          }
          //to this
          thumbs
            .find(".owl-item")
            .removeClass("current")
            .eq(current)
            .addClass("current");
          var onscreen = thumbs.find(".owl-item.active").length - 1;
          var start = thumbs
          .find(".owl-item.active")
          .first()
          .index();
          var end = thumbs
          .find(".owl-item.active")
          .last()
          .index();

          if (current > end) {
            thumbs.data("owl.carousel").to(current, 100, true);
          }
          if (current < start) {
            thumbs.data("owl.carousel").to(current - onscreen, 100, true);
          }
        }

        function syncPosition2(el) {
          if (syncedSecondary) {
            var number = el.item.index;
            bigimage.data("owl.carousel").to(number, 100, true);
          }
        }

        thumbs.on("click", ".owl-item", function(e) {
          e.preventDefault();
          var number = $(this).index();
          bigimage.data("owl.carousel").to(number, 300, true);
        });
    });
</script>

{% endblock %}