penal/urls.py
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path(_('admin/'), admin.site.urls),
    
]
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('' , include('account.urls' , namespace="account")) ,
    path('' , include('df_user.urls' , namespace="df_user")) ,
    path('' , include('driver.urls' , namespace="driver")) ,
    path('' , include('labour_contructor.urls' , namespace="labour_contructor")) ,
    path('' , include('sub_contructor.urls' , namespace="sub_contructor")) ,
    path('' , include('vehicle_owner.urls' , namespace="vehicle_owner")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sub_contructor/urls.py
from django.urls import path 


from sub_contructor.api.register.register import subcontructor_registration ,subcontructor_Address , subcontructordashboard
from sub_contructor.api.payment.payment import subcontructor_payment_api , subcontructor_paymenthandller
from sub_contructor.api.requested_subcon.req_subcon import request_subcontructor_api
from sub_contructor.api.register.update_subcontructor import subcontructor_update_api


## WEB URLS IMORT

from sub_contructor.web.sub import add_subcontructor_view , add_subcontructor_address, update_subcotructor_profile
from sub_contructor.web.sub_payment import subcontructor_making_payment,subcontrctor_payhandler
from sub_contructor.web.subconturctor_request import request_subcontructor_view
from sub_contructor.web.dashboard import subcontructor_dashboard , subcontructor_view



# from driver.api.payment.payment import driver_paymenthandller , driver_payment_api
app_name = 'sub_contructor'

urlpatterns = [
        
        ## Web 

        path('add-subcontructor/' , add_subcontructor_view , name="add_subcontructor_view"),
        path('add-subcontructor-address/' , add_subcontructor_address , name="add_subcontructor_address"),
        path('update-subcontructor-profile/<int:pk>/' , update_subcotructor_profile , name="update_subcotructor_profile"),

        path('subcontructor-view/<int:pk>/' , subcontructor_view , name="subcontructor_view"),
        path('subcontructor_request_view/<int:pk>/' , request_subcontructor_view , name="subcontructor_request_view"),

        path('subcontructor-web-dashboard/' , subcontructor_dashboard , name="subcontructor_dashboard"),

        path('subcontructor-payment/' , subcontructor_making_payment , name="subcontructor_making_payment"),
        path('subcontructor-payhandler/', subcontrctor_payhandler , name="subcontrctor_payhandler"),

        

        ## APIS

        path('subcontructor-registration/' , subcontructor_registration) ,
        path('subcontructor_Address/', subcontructor_Address),
        path('subcontructor-payment-api/' ,subcontructor_payment_api) ,
        path('subcontructor-paymenthandller/' ,subcontructor_paymenthandller) ,
        path('request-subcontructor/' , request_subcontructor_api) ,
        path('subcontructor-dashboard/' ,subcontructordashboard ) ,
        path('subcontructor_update_api/' , subcontructor_update_api),


]

sub_contructor/models.py
from django.db import models
from account.models import *




class subcontractorregistration(models.Model):
    user           = models.ForeignKey(User , on_delete=models.CASCADE)

    contractorname = models.CharField(max_length=100)
    firmname       = models.CharField(max_length=500)
    typeofwork     = models.CharField(max_length=100)
    emailId        = models.CharField(max_length=50 , null=True , blank=True)
    expriencesinyear = models.IntegerField(blank=False, null=False)
    license_number   = models.CharField(max_length=50)
    Aadharnumberfrontimage = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    Aadharnumberbackimage  = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    mobilenumber           = models.CharField(max_length=20)
    subcontractor_image    = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    subcontractor_image_back = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    subcontractor_image_left = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    subcontractor_image_right = models.ImageField(upload_to="Subcontructor-Owners/UserProfiles/")
    is_active                 =    models.BooleanField(default=1,null=False)
    subcontructor_paid        = models.BooleanField(default=False)   
    expired_at                = models.DateField(null=True , blank=True)
    class Meta:
        verbose_name_plural = 'subcontructor_Profile'
        db_table = "subcontractorregistration"
    def __str__(self):
        return self.contractorname +' > '+ self.mobilenumber

        

class subcontructor_Address(models.Model):
    user = models.ForeignKey(subcontractorregistration , on_delete=models.CASCADE, related_name="SubcotructorAddress")
    state_id = models.ForeignKey(state , on_delete=models.CASCADE)
    district_id = models.ForeignKey(district , on_delete=models.CASCADE)
    tahseel_id = models.ForeignKey(tahseel , on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    
    
    class Meta:
        verbose_name_plural = 'SubContructor Address'
        db_table = 'subcontructoraddress'



class subcontructor_payment_amount(models.Model):
    value = models.IntegerField()
    
    
    class Meta:
        verbose_name_plural =  "Add  Payment For Subcontructor"
        db_table = 'subcontructor_payment_amount'



class subcontructor_payment(models.Model):
    user = models.ForeignKey(subcontractorregistration ,
                              on_delete=models.CASCADE , 
                              related_name="subcontructor_payment") 
    razorpay_order_id =  models.CharField(max_length=100)

    payment_id = models.CharField(max_length=100 , null=True , blank=True)
    
    amount =  models.IntegerField()
    discount = models.IntegerField(default=0)

    status = models.BooleanField(default=False)

    recycle = models.IntegerField(default=1)

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural =  "subcontructor Payment"
        db_table = 'subcontructor_payment'

    def __str__(self):
        return self.user.user.mobile_number +'>>'+ str(self.amount)


class request_subcontructor(models.Model):
    user =  models.ForeignKey(profileofall ,  
                              on_delete=models.CASCADE ,
                              )
    subcontractorregistration = models.ForeignKey(subcontractorregistration ,  
                                                on_delete=models.CASCADE ,
                                                related_name= "requested_subcontructor"
                                                 
                                                 )
    reserved = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural =  "Requested Subcontructor"
        db_table = 'request_subcontructor'

    def __str__(self):
        return self.user.user.first_name +" >>"+ self.subcontractorregistration.contractorname

sub_contructor/forms.py
from .models import *
from django import forms



class AddSubcontructorForm(forms.ModelForm):
    class Meta:
        model = subcontractorregistration
        exclude = ('user', 'expired_at','subcontructor_paid' ,'is_active')

        widgets = {
            'contractorname':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'firmname':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'typeofwork':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'emailId':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'expriencesinyear':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'license_number':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'mobilenumber':forms.TextInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'subcontractor_image':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'subcontractor_image_back':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'subcontractor_image_left':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'subcontractor_image_right':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),

            'Aadharnumberfrontimage':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
            'Aadharnumberbackimage':forms.FileInput(attrs={'class':'form-control mb-3' , 'placeholder':''}),
        }
        

sub_contructor/views.py
from django.shortcuts import render

# Create your views here.

sub_contructor/templates/subcontructor-profile.html
{% extends "base.html" %}
{% load static %} 
{% block content %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{request.user.first_name}}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">User Profile</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">
                <!-- Profile Image -->
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light d-flex">
                        <!-- <div class="card-title">
                            <i class="fas fa-newspaper" style="margin-right: 5px;"></i>
                            Edit News
                        </div> -->

                        <div class="mr-auto">
                          <span class="font-weight-bold">Current Status : </span> 
                          <span class="badge rounded-pill pt-1 pb-1 pl-3 pr-3 badge-info elevation-1">Active</span>
                        </div>

                        <div class="ml-auto">
                          <a class="btn btn-sm btn-primary" href="{% url 'sub_contructor:update_subcotructor_profile' subcotructor.id %}"><i class="nav-icon fas fa-edit" style="margin-right: 5px;"></i>Edit Profile</a>
                        </div>
                    </div>

                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="{{subcotructor.subcontractor_image.url}}" alt="User-Profile-Picture">
                        </div>

                        <h3 class="profile-username text-center">{{subcotructor.contractorname}}</h3>
                        <hr>

                        <div class="row">
                          <div class="col-lg-6 col-md-6">
                           
                            <div class="form-group">
                              <label class="font-weight-bold">Mobile Number : </label>
                              <label>{{request.user.mobile_number}}</label>
                            </div>
                            <div class="form-group">
                              <label class="font-weight-bold">Firm Name : </label>
                              <label>{{subcotructor.firmname}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Type Of Work : </label>
                                <label>{{subcotructor.typeofwork}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Experience in Years : </label>
                                <label>{{subcotructor.expriencesinyear}}</label>
                            </div>
                            
                            <div class="form-group">
                              <label class="font-weight-bold">Payment Status : </label>
                              <span class="badge rounded-pill pt-1 pb-1 pl-3 pr-3 badge-success elevation-1">Paid</span>
                            </div>
                          </div>

                          <div class="col-lg-6 col-md-6">
                            
                            <div class="form-group">
                              <label class="font-weight-bold">Mobile Number : </label>
                              <label>{{subcotructor.mobilenumber}}</label>
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Email-ID  : </label>
                                <label>{{subcotructor.emailId}}</label>
                            </div>
                            
                            
                            <div class="form-group">
                                <label class="font-weight-bold">Expired  Date : </label>
                                <label>{{subcotructor.expired_at}}</label>
                            </div>
                            <div class="form-group">
                              <label class="font-weight-bold">License Number: </label>
                              <label>{{subcotructor.license_number}}</label>
                            </div>
                          
                          </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Aadhar Card Front Side
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{subcotructor.Aadharnumberfrontimage.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                    <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Aadhar Card Back Side
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{subcotructor.Aadharnumberbackimage.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="card card-dark card-outline">
                  <div class="card-header bg-light">
                        <i class="fas fa-image" style="margin-right: 5px;"></i>
                        Subcontractor Left Image 
                    </div>

                    <div class="card-body">
                        <div class="image-aspect">
                            <img src="{{subcotructor.subcontractor_image_left.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="col-lg-6 col-md-6">
              <div class="card card-dark card-outline">
                <div class="card-header bg-light">
                      <i class="fas fa-image" style="margin-right: 5px;"></i>
                      Subcontractor Right Image 
                  </div>

                  <div class="card-body">
                      <div class="image-aspect">
                          <img src="{{subcotructor.subcontractor_image_right.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                      </div>
                  </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-6">
              <div class="card card-dark card-outline">
                <div class="card-header bg-light">
                      <i class="fas fa-image" style="margin-right: 5px;"></i>
                      Subcontractor Back Image 
                  </div>

                  <div class="card-body">
                      <div class="image-aspect">
                          <img src="{{subcotructor.subcontractor_image_back.url}}" width="100%" height="100%" class="img-responsive rounded" alt="image">
                      </div>
                  </div>
              </div>
            </div>

           
        </div>
        <!-- /.row -->

      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock %}

sub_contructor/templates/subcontructor-view.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">SubContractor Details</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">SubContractor Details</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
  
    <!-- Main content -->
    <div class="content">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="container-fluid">
        <h2>{{message}}</h2>
        <!-- Heavy Vehicles -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Heavy Vehicles -->
                <div class="card card-dark card-outline">
                    <div class="card-body">
                      {% comment %} {% for i in dr %} {% endcomment %}
                        <div class="row">
                          <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="outer">
                              <div id="big" class="owl-carousel owl-theme">
                              {% if subcon.subcontractor_image %}
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image.url}}" class="rounded rounded-5">
                                </div>
                              {% comment %} {%else%} {% endcomment %}
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_left.url}}" class="rounded rounded-5">
                                </div>
                              {% comment %} {% endif %} {% endcomment %}
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_right.url}}" class="rounded rounded-5">
                                </div>
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_back.url}}" class="rounded rounded-5">
                                </div>
                              </div>

                              <div id="thumbs" class="owl-carousel owl-theme">
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_left.url}}" class="rounded rounded-5">
                                </div>
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_right.url}}" class="rounded rounded-5">
                                </div>
                                <div class="item image-aspect">
                                  <img src="{{subcon.subcontractor_image_back.url}}" class="rounded rounded-5">
                                </div>
                                {% else %}
                                  <img src="" class="rounded rounded-5">
                                {% endif %}
                              </div>
                            </div>
                          </div>

                          <div class="col-lg-6 col-md-6 col-sm-12">
                            
                              <p class="card-text mb-0"></p>

                              <div class="card card-dark shadow">
                                  <div class="card-header">
                                      <h6 class="card-title"><i class="fas fa-user-circle mr-2"></i>Owner and Vehicle Details</h6>
          
                                      <div class="card-tools">
                                          <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                          <i class="fas fa-minus"></i>
                                          </button>
                                      </div>
                                      <!-- /.card-tools -->
                                  </div>
                                  <!-- /.card-header -->

                                  <div class="card-body ">
                                        <p class="card-text font-weight-bold">SubContractor Name &nbsp; : &nbsp; {{subcon.contractorname}}</p>

                                        <p class="card-text mb-0">Type Of Work &nbsp; : &nbsp;  {{subcon.typeofwork}}</p>
                                        <p class="card-text mb-0">Firm Name &nbsp; : &nbsp;  {{subcon.firmname}}</p>
                                        
                                        <p class="card-text mb-0">Experience(InYears) &nbsp; : &nbsp;  {{subcon.expriencesinyear}}</p>
                                        {% for ad in subcon.SubcotructorAddress.all %}
                                        <p class="card-text mb-0">Location &nbsp; : &nbsp;  {{ad.state_id}}  {{ad.district_id}}</p>
                                        {% endfor %}  
                                        {% if reh.reserved %}
                                        <p class="card-text font-weight-bold">Status &nbsp; : &nbsp;  Reserved</p>
                                        <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Reserved</a></button>
                                        {% else %}
                                      
                                        {% if request.user == subcon.user %}
                                        <p class="card-text font-weight-bold">Status &nbsp; : &nbsp;  Not Reserved</p>
                                        <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Request</a></button>

                                        {% else %}

                                          {% if request.user == reh.user.user %}
                                          <p class="card-text font-weight-bold">Status: Not Reserved</p>
                                          <button type="submit" href="#" class="btn bg-yellow elevation-2"disabled>Pending</a></button>

                                          {% else %}

                                          <p class="card-text font-weight-bold">Status: Not Reserved</p>
                                          <a class="btn bg-yellow elevation-2" href="{% url 'sub_contructor:subcontructor_request_view' subcon.id %}">
                                            Request
                                          </a>
                                        
                                          
                                          {% endif %}

                                          

                                        {% endif %}



                                      {% endif %}
                                          
                                        <a href="{% url 'sub_contructor:subcontructor_dashboard' %}" class="btn btn-danger elevation-2 ml-2">Go Back</a>
                                    </div>

                                  <!-- /.card-body -->
                              </div>
                            </div>
                              <!-- /.card -->
                              {% comment %} {% endfor %} {% endcomment %}
                           
                          </div>
                        </div>
                    </div>
                </div><!-- /.card -->
            </div>
            <!-- /.col-md-12 -->
        </div>
        <!-- /.row -->
        </form>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
 

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/js/adminlte.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.3/owl.carousel.min.js"></script>

<script>
    $(document).ready(function() {
        var bigimage = $("#big");
        var thumbs = $("#thumbs");
        var syncedSecondary = true;

        bigimage
          .owlCarousel({
          items: 1,
          slideSpeed: 2000,
          nav: true,
          autoplay: true,
          dots: false,
          loop: true,
          responsiveRefreshRate: 200,
          navText: [
            '<i class="fa fa-arrow-left" aria-hidden="true"></i>',
            '<i class="fa fa-arrow-right" aria-hidden="true"></i>'
          ]
        })
          .on("changed.owl.carousel", syncPosition);

        thumbs
          .on("initialized.owl.carousel", function() {
          thumbs
            .find(".owl-item")
            .eq(0)
            .addClass("current");
        })
          .owlCarousel({
          items: 3,
          dots: true,
          nav: true,
          navText: [
            '<i class="fa fa-arrow-left" aria-hidden="true"></i>',
            '<i class="fa fa-arrow-right" aria-hidden="true"></i>'
          ],
          smartSpeed: 200,
          slideSpeed: 500,
          slideBy: 4,
          responsiveRefreshRate: 100
        })
          .on("changed.owl.carousel", syncPosition2);

        function syncPosition(el) {
          //if loop is set to false, then you have to uncomment the next line
          //var current = el.item.index;

          //to disable loop, comment this block
          var count = el.item.count - 1;
          var current = Math.round(el.item.index - el.item.count / 2 - 0.5);

          if (current < 0) {
            current = count;
          }
          if (current > count) {
            current = 0;
          }
          //to this
          thumbs
            .find(".owl-item")
            .removeClass("current")
            .eq(current)
            .addClass("current");
          var onscreen = thumbs.find(".owl-item.active").length - 1;
          var start = thumbs
          .find(".owl-item.active")
          .first()
          .index();
          var end = thumbs
          .find(".owl-item.active")
          .last()
          .index();

          if (current > end) {
            thumbs.data("owl.carousel").to(current, 100, true);
          }
          if (current < start) {
            thumbs.data("owl.carousel").to(current - onscreen, 100, true);
          }
        }

        function syncPosition2(el) {
          if (syncedSecondary) {
            var number = el.item.index;
            bigimage.data("owl.carousel").to(number, 100, true);
          }
        }

        thumbs.on("click", ".owl-item", function(e) {
          e.preventDefault();
          var number = $(this).index();
          bigimage.data("owl.carousel").to(number, 300, true);
        });
    });
</script>

</body>
</html>


{% endblock %}